### ISSUE TITLE
Support resizing fzfx popup window when Neovim is resized

### ISSUE THREAD

**Issue by jetm** [linrongbin16/fzfx.nvim#312]
The fzfx live_grep feature works very well. I have tested several live_grep implementations under Telescope, and I found fzfx to be better. I can easily change the search query. Thanks you!

Do you plan to add resize query result support when Neovim is maximized?

The case is using Neovim under Tmux in one pane. When the pane is maximized, Neovim width is expanded too, but the fzfx live_grep results are not.

**Comment by linrongbin16** [comment]
Hi @jetm , support tmux should be good, would you please help me define some details (since I'm not expert on tmux)?

1. You start a terminal maximized, and start a tmux pane and split the terminal into two parts (vertical or horizontal), and even split terminal into multiple small parts.
2. In one of the tmux pane, you start running neovim, and inside it you start fzfx to do live grep?

Is that correct?

**Comment by linrongbin16** [comment]
Oh, I think I got your point, you mean when a popup window is already opened, and tmux pane is resized (or a terminal window that running neovim is resized), the fzfx popup window could re-calculate the popup window size and do resize!

I think I could listen to the Neovim Editor/Window changed event, and do resize.

**Comment by jetm** [comment]
> Is that correct?

Yes, that's correct

**Comment by jetm** [comment]
> a terminal window that running neovim is resized

Yes, a terminal window is a commoner case than using tmux.

I believe this is how Telescope does the resizing: https://github.com/nvim-telescope/telescope.nvim/commit/adfbd616c691add448ff1b2ed7dfa1a9d84204d9. But I don't know how to replicate the same work on fzfx

**Comment by linrongbin16** [comment]
Hi @jetm , I add realtime resize popup window feature in #322 , would you please pull latest main branch and try?
