### ISSUE TITLE
Back action in `FzfxFileExplorer` does not work if directory is empty

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#507]
Steps to reproduce:

1. `cd` into subdirectory that is empty
2. Press "go up" hotkey
3. Nothing happens

Is not affected by the https://github.com/linrongbin16/fzfx.nvim/issues/506 change.

**Comment by linrongbin16** [comment]
thanks for your report! it's really an edge case that I didn't notice.

after debugging for several hours, I still didn't find the root cause.

but I guess if there's an exception failure, because there's an `assert` failed in the interaction rpc callback, then the whole plugin popup is lost. e.g. whatever the keys I press, there's no logging or other things.

**Comment by linrongbin16** [comment]
After add more logging and debug again, I found the interaction RPC call actually doesn't send to nvim server at all.

That could relate to fzf's behavior, because there're no lines in left side.

**Comment by linrongbin16** [comment]
> > That could relate to fzf's behavior, e.g. the binded key 'ctrl-h' is not working
> 
> For what it's worth, `fzf --bind=ctrl-h:accept` works just fine.

no, after doing more debugging and investigation, I'm pretty sure that, when there's no lines in left side of fzf, then press 'CTRL-H', the callback functions are not been invoked.

The details of the `press 'CTRL-H' to upper` is:

1. fzf is binding with `--bind=ctrl-h:execute-silent(...)`
2. inside the execute-silent, the real shell command is: `nvim -l -u NONE .../bin/rpc/request.lua <rpc-id> {}`
3. The last parameter `{}` is the placeholder, fzf will pass the current selected line to the `.../bin/rpc/request.lua` as shell argument.

With debug logging, I'm pretty sure that, for empty directory, since there're no lines in fzf left side, so fzf doesn't actually run the `nvim -l -u NONE .../bin/rpc/request.lua` command, so no interactions are sending to nvim backend, so no callbacks are been called.

To avoid this issue, I will detect if the directory is empty, and disable user to cd into it.

**Comment by linrongbin16** [comment]
Please see: https://linrongbin16.github.io/fzfx.nvim/#/KnownIssues
